export const RECEIVE_ADDRESS = 'receive_address'  // 接收地址信息
export const RECEIVE_CATEGORYS = 'receive_categorys' // 接收商品分类数组
export const RECEIVE_SHOPS = 'receive_shops'  // 接收商家数组
export const RECEIVE_USER = 'receive_user'  // 保存用户信息
export const RESET_USER = 'reset_user'  // 重置用户信息
export const RECEIVE_INFO = 'receive_info'  // 获取mock数据中商家info
export const RECEIVE_GOODS = 'receive_goods'  // 获取mock中商家的食品分类
export const RECEIVE_RATINGS = 'receive_ratings'  // 获取商家的评分
export const INCREMENT_FOOD_COUNT = 'increment_food_count'
export const DECREMENT_FOOD_COUNT = 'decrement_food_count'
